### PR TITLE
suggest edits for creating a permanent cache

### PR DESCRIPTION
**Pull request by oraNod**

### CODE REVIEW

**Comment by oraNod** [comment]
@galderz How is DatagridCfg.java used in this demo?

**Comment by galderz** [comment]
@oraNod Now that master has the final tutorial, fabric8 branch is outdated. Can you look at the README in master branch and see if you want to do any updates? I'll close this for now.

**Comment by galderz** [comment]
DatagridCfg.java encapsulates the client side configuration required to connect to datagrid. It includes authentication information and other encryption related configuration, as well as datagrid host and port info.

**Comment by oraNod** [comment]
> @oraNod Now that master has the final tutorial, fabric8 branch is outdated. Can you look at the README in master branch and see if you want to do any updates? I'll close this for now.

Sorry @galderz I got mixed up and thought the fabric8 branch was for pending changes. I've got a PR for master on the way.

**Pull request closed without merging**
